# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to=b'galeria/%Y/%m/%d/')),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
