# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=b'pic_folder/no-image.png', upload_to=b'pic_folder/'),
        ),
    ]
