# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170904_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('local', models.CharField(max_length=120)),
                ('duracao', models.CharField(max_length=50)),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField()),
            ],
        ),
    ]
