wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-bold.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-bold.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-bold.woff2
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-bold.woff
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-bold.ttf
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-bold.svg
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-light.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-light.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-light.woff2
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-light.woff
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-light.ttf
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-light.svg
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-medium.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-medium.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-medium.woff2
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-medium.woff
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-medium.ttf
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-medium.svg
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-regular.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-regular.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-regular.woff2
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-regular.woff
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-regular.ttf
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-regular.svg
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-semibold.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-semibold.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-semibold.woff2
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-semibold.woff
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-semibold.ttf
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/montserrat-semibold.svg
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-bold.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-bold.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-bold.woff2
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-bold.woff
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-bold.ttf
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-bold.svg
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-light.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-light.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-light.woff2
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-light.woff
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-light.ttf
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-light.svg
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-regular.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-regular.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-regular.woff2
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-regular.woff
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-regular.ttf
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-regular.svg
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-semibold.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-semibold.eot
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-semibold.woff2
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-semibold.woff
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-semibold.ttf
wget http://themes.a3devs.com/tf/html/dentalhome/fonts/opensans-semibold.svg
